DROP TABLE IF EXISTS task;
DROP TABLE IF EXISTS task_log;
DROP TABLE IF EXISTS daily_status;

CREATE TABLE task (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_id INTEGER,
  project_name TEXT,
  version TEXT,
  opt_id INTEGER,
  task_status TEXT,
  task_name TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE task_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  task_id INTEGER NOT NULL,
  previous_status TEXT,
  current_status TEXT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (task_id) REFERENCES task (id)
);

CREATE TABLE daily_status (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TIMESTAMP NOT NULL,
  status TEXT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);